version: '3'

services:
  app_redis:
    image: redis:6.0-alpine
    command: redis-server
    volumes:
      - ./tmp/redis:/var/shared/redis
  app_db:
    image: postgres:12.5-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./tmp/shared:/var/shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  bob:
    build:
      context: ./bob
      dockerfile: Dockerfile
    container_name: bob
    volumes:
      - ./bob:/var/app
      - ./tmp/shared:/var/shared
      - ./tmp/gems:/bundle/vendor
    ports:
      - 3010:3000
    stdin_open: true
    tty: true
    env_file: .env.dev
    entrypoint: ["dev-entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - app_db
  alice:
    build:
      context: ./alice
      dockerfile: Dockerfile
    container_name: alice
    volumes:
      - ./alice:/var/app
      - ./tmp/shared:/var/shared
      - ./tmp/gems:/bundle/vendor
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.dev
    entrypoint: ["dev-entrypoint.sh"]
    command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - app_db
      - bob
      - app_redis
  pgadmin:
    image: dpage/pgadmin4:5
    restart: always
    depends_on: 
      - app_db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: superSecret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    logging:
      driver: none
  alice_test:
    image: alice_bob_test_alice
    volumes:
      - ./alice:/var/app
      - ./tmp/shared:/var/shared
      - ./tmp/gems:/bundle/vendor
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    depends_on:
      - app_db
      - app_redis
